/**
 * VeritaAssure(TM) PI Dashboard - Performance Improvement Metric Starter Library
 *
 * 161 metrics across 11 departments, drawn from CAP Q-Probes/Q-Tracks,
 * AABB Standards, CLSI, CLIA, TJC NPSGs, ISO 15189, and other published sources.
 */

export interface StarterMetric {
  department: string;
  name: string;
  phase: "pre-analytical" | "analytical" | "post-analytical";
  unit: string;
  direction: "lower_is_better" | "higher_is_better";
  benchmark: string;
  source: string;
}

export const PI_STARTER_LIBRARY: StarterMetric[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 1 - Blood Bank / Transfusion Medicine (26 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Wrong Blood in Tube (WBIT) Rate",
    phase: "pre-analytical",
    unit: "Errors per 1,000 specimens",
    direction: "lower_is_better",
    benchmark: "0.43 per 1,000 (CAP Q-Probes median); goal: zero",
    source: "CAP Q-Probes 2017",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Blood Bank Mislabeled Specimen Rate",
    phase: "pre-analytical",
    unit: "Mislabeled specimens per 1,000 specimens",
    direction: "lower_is_better",
    benchmark: "Median: 7.4 per 1,000; goal: zero",
    source: "CAP Q-Probes 2017",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Specimen Rejection Rate (blood bank)",
    phase: "pre-analytical",
    unit: "% specimens rejected",
    direction: "lower_is_better",
    benchmark: "0.2-0.75%",
    source: "CAP Q-Probes; AABB Standards 34th ed.",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "ABO/Rh Typing Discrepancy Rate",
    phase: "analytical",
    unit: "Discrepancies per total specimens tested",
    direction: "lower_is_better",
    benchmark: "Goal: zero ABO-incompatible releases",
    source: "AABB Standards 34th ed.; ISO 15189",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Crossmatch-to-Transfusion (C:T) Ratio",
    phase: "pre-analytical",
    unit: "Ratio (unitless)",
    direction: "lower_is_better",
    benchmark: "Goal: <2.0; top 10%: <1.5",
    source: "CAP Q-Probes; AABB",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Crossmatch-to-Issue (C:I) Ratio",
    phase: "analytical",
    unit: "Ratio (unitless)",
    direction: "lower_is_better",
    benchmark: "Target: <1.15",
    source: "International survey; CAP TODAY",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Transfusion Index",
    phase: "post-analytical",
    unit: "Mean units transfused per patient crossmatched",
    direction: "higher_is_better",
    benchmark: ">=0.5 considered appropriate; target approaches 1.0",
    source: "JCDR; CAP Q-Probes",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Blood Utilization Rate (% transfused)",
    phase: "post-analytical",
    unit: "% of crossmatched units actually transfused",
    direction: "higher_is_better",
    benchmark: ">=30% minimum; top performers: >=70%",
    source: "JCDR 2022; AABB",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "RBC Expiration Rate",
    phase: "post-analytical",
    unit: "% of RBC units expired before use",
    direction: "lower_is_better",
    benchmark: "<1%",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "RBC Wastage Rate (non-expiration)",
    phase: "post-analytical",
    unit: "% of RBC units wasted (not from expiration)",
    direction: "lower_is_better",
    benchmark: "<0.5% (top performers); <1% achievable",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Platelet Expiration Rate",
    phase: "post-analytical",
    unit: "% of platelet units expired",
    direction: "lower_is_better",
    benchmark: "Top performers: <0.6%; achievable: <1%",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Platelet Wastage Rate (non-expiration)",
    phase: "post-analytical",
    unit: "% of platelets wasted (non-expired)",
    direction: "lower_is_better",
    benchmark: "Top performers: <0.5%",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Fresh Frozen Plasma (FFP) Expiration Rate",
    phase: "post-analytical",
    unit: "% FFP expired before use",
    direction: "lower_is_better",
    benchmark: "Achievable: <1%",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "FFP Wastage Rate (non-expiration)",
    phase: "post-analytical",
    unit: "% FFP wasted (non-expired)",
    direction: "lower_is_better",
    benchmark: "Achievable: <0.5%",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Overall Blood Product Discard Rate",
    phase: "post-analytical",
    unit: "% of total units discarded",
    direction: "lower_is_better",
    benchmark: "Top centers: <2-3%; US avg ~5.85%",
    source: "AABB survey data",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Adverse Transfusion Reaction Rate",
    phase: "post-analytical",
    unit: "Reactions per 1,000 components transfused",
    direction: "lower_is_better",
    benchmark: "US rate: ~2.5-2.8 per 1,000",
    source: "AABB Blood Survey; NBCUS 2017",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Near-Miss Event Rate (transfusion)",
    phase: "pre-analytical",
    unit: "Events per 10,000 requests",
    direction: "lower_is_better",
    benchmark: "~0.034% prevalence (1 in 2,916 requests)",
    source: "Oman Medical Journal 2021; Viamedica",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Type and Screen Completion >=1 Day Prior to Surgery",
    phase: "pre-analytical",
    unit: "% of T&S tests completed >=1 day pre-surgery",
    direction: "higher_is_better",
    benchmark: "Median: ~69%; with protocol: ~74-87%",
    source: "CAP Q-Probes 2003",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Surgery Delay Due to Same-Day T&S Rate",
    phase: "pre-analytical",
    unit: "% of same-day T&S cases causing surgery delay",
    direction: "lower_is_better",
    benchmark: "0.8% of cases",
    source: "CAP Q-Probes 2003",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Operating Room Blood Delivery Turnaround Time",
    phase: "post-analytical",
    unit: "Minutes from order to OR delivery",
    direction: "lower_is_better",
    benchmark: "Institution-defined",
    source: "CAP Q-Probes 2002",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Plasma Transfusion Guideline Compliance Rate",
    phase: "analytical",
    unit: "% compliance with plasma transfusion audit criteria",
    direction: "higher_is_better",
    benchmark: "Institution-defined",
    source: "CAP Q-Probes 2017",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "RBC Transfusion Audit Compliance Rate",
    phase: "analytical",
    unit: "% compliance with RBC transfusion audit criteria",
    direction: "higher_is_better",
    benchmark: "Institution-defined",
    source: "CAP Q-Probes 2015",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Patient Identification Compliance Rate During Transfusion",
    phase: "pre-analytical",
    unit: "% of transfusions with documented proper patient ID",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP Q-Probes 2003",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Vital Sign Monitoring Compliance During Transfusion",
    phase: "post-analytical",
    unit: "% of transfusions with documented vital sign monitoring",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP Q-Probes 2003",
  },
  {
    department: "Blood Bank / Transfusion Medicine",
    name: "Donor Adverse Reaction Rate",
    phase: "analytical",
    unit: "Reactions per 1,000 donation procedures",
    direction: "lower_is_better",
    benchmark: "22.8 per 1,000; range 7.0-37.3/1,000",
    source: "AABB Donor Hemovigilance Report 2014",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 2 - Core Lab (Chemistry, Hematology, Urinalysis, Coagulation) (27 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Core Lab",
    name: "ED Stat Hemoglobin Turnaround Time (TAT)",
    phase: "analytical",
    unit: "Minutes, phlebotomy to result",
    direction: "lower_is_better",
    benchmark: "Median: 25 min; 90% within <=39 min",
    source: "CAP Q-Probes 1992/1997",
  },
  {
    department: "Core Lab",
    name: "ED Stat Potassium Turnaround Time (TAT)",
    phase: "analytical",
    unit: "Minutes, phlebotomy to result",
    direction: "lower_is_better",
    benchmark: "Median: 36 min; 90% within <=53 min",
    source: "CAP Q-Probes 1992/1997",
  },
  {
    department: "Core Lab",
    name: "ED Stat Creatinine Order-to-Report TAT",
    phase: "analytical",
    unit: "Minutes, order to result",
    direction: "lower_is_better",
    benchmark: "Median: 48 min; best: 35 min",
    source: "CAP Q-Probes ~2011",
  },
  {
    department: "Core Lab",
    name: "ED Stat CBC Order-to-Report TAT",
    phase: "analytical",
    unit: "Minutes, order to result",
    direction: "lower_is_better",
    benchmark: "Median: 31 min; best: 22 min",
    source: "CAP Q-Probes ~2011",
  },
  {
    department: "Core Lab",
    name: "ED Stat Urine Microscopy Order-to-Report TAT",
    phase: "analytical",
    unit: "Minutes, order to result",
    direction: "lower_is_better",
    benchmark: "Median: 46 min; best: 25 min",
    source: "CAP Q-Probes ~2011",
  },
  {
    department: "Core Lab",
    name: "Stat Potassium Outlier TAT Rate",
    phase: "post-analytical",
    unit: "% of stat potassium results exceeding deadline",
    direction: "lower_is_better",
    benchmark: "Overall outlier rate: 14.8%",
    source: "CAP Q-Tracks 2004",
  },
  {
    department: "Core Lab",
    name: "Routine Morning Test Outlier TAT Rate",
    phase: "post-analytical",
    unit: "% of routine test results exceeding deadline",
    direction: "lower_is_better",
    benchmark: "Overall outlier rate: 11.7%",
    source: "CAP Q-Tracks 2004",
  },
  {
    department: "Core Lab",
    name: "Morning Rounds BUN Availability Time",
    phase: "post-analytical",
    unit: "Clock time at which 90% of results are available",
    direction: "lower_is_better",
    benchmark: "Median: by 09:04",
    source: "CAP Q-Probes 2000",
  },
  {
    department: "Core Lab",
    name: "Morning Rounds WBC Availability Time",
    phase: "post-analytical",
    unit: "Clock time at which 90% of results are available",
    direction: "lower_is_better",
    benchmark: "Median: by 08:51",
    source: "CAP Q-Probes 2000",
  },
  {
    department: "Core Lab",
    name: "Stat Troponin Order-to-Report TAT",
    phase: "analytical",
    unit: "Minutes, order to result",
    direction: "lower_is_better",
    benchmark: "Median: 39 min; CAP target: <=60 min",
    source: "CAP Q-Probes 2004",
  },
  {
    department: "Core Lab",
    name: "Stat CK-MB Order-to-Report TAT",
    phase: "analytical",
    unit: "Minutes, order to result",
    direction: "lower_is_better",
    benchmark: "75th pctile: median <=48.3 min",
    source: "CAP Q-Probes 2004",
  },
  {
    department: "Core Lab",
    name: "Critical Value Notification Time",
    phase: "post-analytical",
    unit: "Minutes from test completion to clinician notification",
    direction: "lower_is_better",
    benchmark: "Median: 5 min; IQR: 1.5-8 min",
    source: "CAP Q-Probes 2008",
  },
  {
    department: "Core Lab",
    name: "Specimen Labeling Error Rate",
    phase: "pre-analytical",
    unit: "Errors per 1,000 labels",
    direction: "lower_is_better",
    benchmark: "0.92 per 1,000 labels",
    source: "CAP Q-Probes 2008",
  },
  {
    department: "Core Lab",
    name: "Manual Peripheral Blood Smear Review Rate",
    phase: "analytical",
    unit: "% of automated CBCs receiving manual review",
    direction: "lower_is_better",
    benchmark: "Median: 26.7%; aggregate: 16.2%",
    source: "CAP Q-Probes 2006",
  },
  {
    department: "Core Lab",
    name: "Hemolysis Rate",
    phase: "pre-analytical",
    unit: "% of specimens with significant hemolysis",
    direction: "lower_is_better",
    benchmark: "<3% achievable; ED potassium: <2%",
    source: "CAP Q-Probes 2015",
  },
  {
    department: "Core Lab",
    name: "Delta Check Alert Investigation Rate",
    phase: "analytical",
    unit: "% of delta check flags investigated and resolved",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP Q-Probes 2017",
  },
  {
    department: "Core Lab",
    name: "Internal QC Out-of-Range Rate",
    phase: "analytical",
    unit: "% of QC runs falling outside control limits",
    direction: "lower_is_better",
    benchmark: "Six-sigma target: <1%",
    source: "CLIA 42 CFR 493.1256; CAP LAP",
  },
  {
    department: "Core Lab",
    name: "QC Corrective Action Documentation Rate",
    phase: "analytical",
    unit: "% of QC failures with documented corrective action",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1289; CAP LAP",
  },
  {
    department: "Core Lab",
    name: "Calibration and Calibration Verification Compliance Rate",
    phase: "analytical",
    unit: "% of scheduled events completed on time",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1255; CLIA; CAP LAP",
  },
  {
    department: "Core Lab",
    name: "Routine Inpatient STAT TAT",
    phase: "analytical",
    unit: "Hours from receipt to resulted report",
    direction: "lower_is_better",
    benchmark: "<=1 hour for STAT samples",
    source: "CLIA 42 CFR 493.1299",
  },
  {
    department: "Core Lab",
    name: "Routine Inpatient Test TAT (non-STAT)",
    phase: "analytical",
    unit: "Hours from receipt to resulted report",
    direction: "lower_is_better",
    benchmark: "90% within 5-6 hours from receipt",
    source: "CLIA 42 CFR 493.1299",
  },
  {
    department: "Core Lab",
    name: "INR ISI/PT Mean Verification Compliance",
    phase: "analytical",
    unit: "Documented verifications per reagent lot change",
    direction: "higher_is_better",
    benchmark: "At least twice annually per CLIA",
    source: "CLIA 42 CFR 493.1289; COLA",
  },
  {
    department: "Core Lab",
    name: "Method Performance Verification Completion Rate",
    phase: "analytical",
    unit: "% of new test systems verified before patient use",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1253; CLSI EP15-A3; CAP LAP",
  },
  {
    department: "Core Lab",
    name: "Corrected/Amended Report Rate (clinical pathology)",
    phase: "post-analytical",
    unit: "% of finalized reports with post-release amendments",
    direction: "lower_is_better",
    benchmark: "Target: <0.25%; >0.5% signals systemic issues",
    source: "42 CFR 493.1299",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 3 - Microbiology (17 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Microbiology",
    name: "Blood Culture Contamination Rate",
    phase: "pre-analytical",
    unit: "% of blood culture sets contaminated",
    direction: "lower_is_better",
    benchmark: "<3% (CLSI M47); <1% aspirational",
    source: "CLSI M47; CAP Q-Probes 1998; Q-Tracks 2005",
  },
  {
    department: "Microbiology",
    name: "Preliminary Blood Culture Gram Stain Reporting TAT",
    phase: "post-analytical",
    unit: "Hours from positivity signal to Gram stain report",
    direction: "lower_is_better",
    benchmark: ">=95% within 2 hours; aspirational: <1 hour",
    source: "ASM CPHMC 2017; CAP Q-Probes 2015",
  },
  {
    department: "Microbiology",
    name: "Blood Culture Organism ID TAT",
    phase: "analytical",
    unit: "Days from collection to organism ID report",
    direction: "lower_is_better",
    benchmark: "Median: 1.81 days",
    source: "JCM 2018; CAP Q-Probes 2015",
  },
  {
    department: "Microbiology",
    name: "Blood Culture Gram Stain TAT",
    phase: "analytical",
    unit: "Days from collection to first Gram stain report",
    direction: "lower_is_better",
    benchmark: "Median: ~0.80 days",
    source: "JCM 2018; CAP Q-Probes 2015",
  },
  {
    department: "Microbiology",
    name: "Blood Culture AST (susceptibility) TAT",
    phase: "analytical",
    unit: "Days from collection to final susceptibility result",
    direction: "lower_is_better",
    benchmark: "Median: 2.71 days; conventional 48-72 hours",
    source: "JCM 2018; PMC Diagnostics 2021",
  },
  {
    department: "Microbiology",
    name: "Gram Stain-to-Final Culture Concordance Rate",
    phase: "analytical",
    unit: "% agreement between Gram stain and final culture",
    direction: "higher_is_better",
    benchmark: "98.8% agreement",
    source: "CAP Q-Probes 2015",
  },
  {
    department: "Microbiology",
    name: "Blood Culture Notification Compliance Rate",
    phase: "post-analytical",
    unit: "% of positive results meeting lab-defined TAT goal",
    direction: "higher_is_better",
    benchmark: "Median lab compliance: 80.9%",
    source: "CAP Q-Probes 2015",
  },
  {
    department: "Microbiology",
    name: "Urine Culture Contamination Rate",
    phase: "pre-analytical",
    unit: "% of urine cultures deemed contaminated",
    direction: "lower_is_better",
    benchmark: "Median: ~15%; goal: <10%",
    source: "CAP Q-Probes 2008; ASM CPHMC 2017",
  },
  {
    department: "Microbiology",
    name: "Solitary (Single-Bottle) Blood Culture Set Rate",
    phase: "pre-analytical",
    unit: "% of collections with a single bottle only",
    direction: "lower_is_better",
    benchmark: "Goal: zero",
    source: "CAP Q-Probes 2001",
  },
  {
    department: "Microbiology",
    name: "AFB Culture Contamination Rate",
    phase: "pre-analytical",
    unit: "% of AFB cultures contaminated",
    direction: "lower_is_better",
    benchmark: "WHO: 2-3%; CDC: 3-5%; liquid media: 7-8%",
    source: "ASM CPHMC 2017",
  },
  {
    department: "Microbiology",
    name: "AFB Smear-to-Culture Correlation Rate",
    phase: "analytical",
    unit: "% agreement between smear and culture results",
    direction: "higher_is_better",
    benchmark: "60-80% smear-positive are true positives on culture",
    source: "ASM CPHMC 2017",
  },
  {
    department: "Microbiology",
    name: "Gram Stain-Culture Correlation Rate (wound/sterile site)",
    phase: "analytical",
    unit: "% non-discrepant results (Gram stain vs. culture)",
    direction: "higher_is_better",
    benchmark: "94-96% non-discrepant",
    source: "ASM CPHMC 2017",
  },
  {
    department: "Microbiology",
    name: "AST QC Strain Acceptable Performance Rate",
    phase: "analytical",
    unit: "% of QC runs within CLSI M100 reference ranges",
    direction: "higher_is_better",
    benchmark: ">=95% within established range",
    source: "CLSI M100; CLSI M23",
  },
  {
    department: "Microbiology",
    name: "Corrected/Amended Report Rate (microbiology)",
    phase: "post-analytical",
    unit: "% of positive culture reports requiring correction",
    direction: "lower_is_better",
    benchmark: "~0.8% of positive reports; ~0.3% clinically significant",
    source: "ASM CPHMC 2017; CAP Q-Probes",
  },
  {
    department: "Microbiology",
    name: "Molecular Assay Invalid Rate (microbiology)",
    phase: "analytical",
    unit: "% of molecular assay runs with invalid results",
    direction: "lower_is_better",
    benchmark: "Platform-specific; tracked internally",
    source: "ASM CPHMC 2017; CLSI MM13",
  },
  {
    department: "Microbiology",
    name: "IGRA Indeterminate Rate",
    phase: "analytical",
    unit: "% of IGRA results indeterminate",
    direction: "lower_is_better",
    benchmark: "Monitored for trend",
    source: "ASM CPHMC 2017",
  },
  {
    department: "Microbiology",
    name: "Disk Diffusion vs. MIC Categorical Agreement Rate",
    phase: "analytical",
    unit: "% categorical agreement between methods",
    direction: "higher_is_better",
    benchmark: ">=90% categorical agreement",
    source: "CLSI; ASM; JCM",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 4 - Cytology (11 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Cytology",
    name: "Unsatisfactory Pap Test Rate",
    phase: "analytical",
    unit: "% of GYN Pap tests reported as unsatisfactory",
    direction: "lower_is_better",
    benchmark: "<=5%; LBC typically 1-2%",
    source: "Bethesda System 2014; CAP LAP",
  },
  {
    department: "Cytology",
    name: "ASC-US Rate",
    phase: "analytical",
    unit: "% of satisfactory specimens diagnosed as ASC-US",
    direction: "lower_is_better",
    benchmark: "CAP range: 2-5% of satisfactory tests",
    source: "CAP LAP CYP.07600",
  },
  {
    department: "Cytology",
    name: "ASC/SIL Ratio",
    phase: "analytical",
    unit: "Ratio",
    direction: "lower_is_better",
    benchmark: "CAP range: 0.4-5.1; target: <2:1 to 3:1",
    source: "CAP LAP CYP.07400",
  },
  {
    department: "Cytology",
    name: "HSIL Detection Rate",
    phase: "analytical",
    unit: "% of satisfactory Pap tests diagnosed as HSIL",
    direction: "higher_is_better",
    benchmark: "Population-dependent; monitored vs. peers",
    source: "CAP LAP CYP.07600; Bethesda System 2014",
  },
  {
    department: "Cytology",
    name: "HR-HPV Positive Rate Among ASC-US Cases",
    phase: "post-analytical",
    unit: "% of ASC-US cases with positive high-risk HPV",
    direction: "lower_is_better",
    benchmark: "Population-dependent; surrogate quality metric",
    source: "CAP LAP CYP.07653",
  },
  {
    department: "Cytology",
    name: "Cytohistologic Correlation (CHC) Rate",
    phase: "post-analytical",
    unit: "% concordance between Pap cytology and biopsy",
    direction: "higher_is_better",
    benchmark: "84.7-100% concordance by category",
    source: "PubMed 2021; CAP LAP",
  },
  {
    department: "Cytology",
    name: "GYN Cytology Turnaround Time",
    phase: "post-analytical",
    unit: "Calendar days from receipt to signed report",
    direction: "lower_is_better",
    benchmark: "Median: <=6 days; 90th pctile: <=8 days",
    source: "CAP Q-Probes 1999",
  },
  {
    department: "Cytology",
    name: "GYN Cytology Negative Rescreen Rate (10% QC)",
    phase: "analytical",
    unit: "% of negative GYN slides re-screened per year",
    direction: "higher_is_better",
    benchmark: "CLIA mandates >=10%; goal: 100% compliance",
    source: "CLIA 1988; CAP LAP CYP.08575",
  },
  {
    department: "Cytology",
    name: "Cytology 5-Year Retrospective Review Completion",
    phase: "analytical",
    unit: "% of required 5-year reviews completed",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CLIA 42 CFR 493.1274; CAP LAP",
  },
  {
    department: "Cytology",
    name: "Non-GYN Cytology Turnaround Time",
    phase: "post-analytical",
    unit: "Calendar days from receipt to signed report",
    direction: "lower_is_better",
    benchmark: "CAP goal: 90% within 2 working days",
    source: "CAP LAP CYP.06532; CAP Q-Probes 2001",
  },
  {
    department: "Cytology",
    name: "Non-GYN Cytology Atypical/Suspicious Diagnosis Rate",
    phase: "analytical",
    unit: "% of NGC cases with atypical/suspicious diagnoses",
    direction: "lower_is_better",
    benchmark: "Monitored vs. peer benchmarks",
    source: "CAP LAP",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 5 - Histology / Surgical Pathology (7 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Histology / Surgical Pathology",
    name: "Surgical Pathology Biopsy TAT (CPT 88305)",
    phase: "post-analytical",
    unit: "Business days from accession to signed-out report",
    direction: "lower_is_better",
    benchmark: ">=90% within 2 business days",
    source: "CAP QCDR Measure CAP22",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Complex/Large Specimen Surgical Pathology TAT",
    phase: "post-analytical",
    unit: "Calendar days from accession to sign-out",
    direction: "lower_is_better",
    benchmark: "Median: 2.72 days; best: 1.22 days",
    source: "CAP Q-Probes",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Frozen Section Turnaround Time",
    phase: "analytical",
    unit: "Minutes from specimen arrival to verbal report",
    direction: "lower_is_better",
    benchmark: ">=90% within 20 minutes",
    source: "CAP LAP; CAP Q-Probes 1997",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Frozen Section Concordance Rate",
    phase: "analytical",
    unit: "% agreement between frozen section and permanent section",
    direction: "higher_is_better",
    benchmark: "98.58% concordance; target: >=97-98%",
    source: "CAP Q-Probes 1996; CAP Q-Tracks",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Amended Report Rate (surgical pathology)",
    phase: "post-analytical",
    unit: "% of finalized reports amended after sign-out",
    direction: "lower_is_better",
    benchmark: "Range: 0.1-10%; benchmark: ~0.33%",
    source: "CAP Q-Probes 2014; CAP Best Practices 2019",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Synoptic Reporting Compliance Rate",
    phase: "post-analytical",
    unit: "% of cancer reports with all mandatory data elements",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP Cancer Protocols; CAP LAP",
  },
  {
    department: "Histology / Surgical Pathology",
    name: "Surgical Pathology Report Defect Rate",
    phase: "post-analytical",
    unit: "Defects per 1,000 reports",
    direction: "lower_is_better",
    benchmark: "Median: 5.7 per 1,000 reports",
    source: "CAP Q-Probes 2014",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 6 - Point-of-Care Testing (11 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Point-of-Care Testing",
    name: "Operator Training/Competency Completion Rate",
    phase: "pre-analytical",
    unit: "% of POCT operators with current documented training",
    direction: "higher_is_better",
    benchmark: "CAP Q-Probes: 94%; goal: 100%",
    source: "CAP Q-Probes 2014; CMS CLIA",
  },
  {
    department: "Point-of-Care Testing",
    name: "POCT QC Documentation Compliance Rate",
    phase: "analytical",
    unit: "% of expected QC events properly documented",
    direction: "higher_is_better",
    benchmark: "CAP Q-Probes: 95.7%; goal: 100%",
    source: "CAP Q-Probes 2014",
  },
  {
    department: "Point-of-Care Testing",
    name: "POCT Operator Identity Documentation Rate",
    phase: "analytical",
    unit: "% of POCT test records documenting operator identity",
    direction: "higher_is_better",
    benchmark: "CAP Q-Probes: 96.8%; goal: 100%",
    source: "CAP Q-Probes 2014",
  },
  {
    department: "Point-of-Care Testing",
    name: "Out-of-Range QC Event Rate (POCT devices)",
    phase: "analytical",
    unit: "% of QC runs falling outside acceptable range",
    direction: "lower_is_better",
    benchmark: "CAP Q-Probes: ~3%; six-sigma: <1%",
    source: "CAP Q-Probes 2014; AACC/ADLM 2020",
  },
  {
    department: "Point-of-Care Testing",
    name: "Out-of-Range QC Follow-Up Documentation Rate",
    phase: "post-analytical",
    unit: "% of out-of-range events with documented follow-up",
    direction: "higher_is_better",
    benchmark: "CAP Q-Probes: 92.6%; goal: 100%",
    source: "CAP Q-Probes 2014",
  },
  {
    department: "Point-of-Care Testing",
    name: "Glucose Meter Correlation with Core Lab",
    phase: "analytical",
    unit: "% of results within acceptable agreement limits",
    direction: "higher_is_better",
    benchmark: "95% within +/-12 mg/dL or +/-12.5%; R >0.95",
    source: "ISO 15197",
  },
  {
    department: "Point-of-Care Testing",
    name: "POCT Analyzer Precision (CV per analyte)",
    phase: "analytical",
    unit: "Coefficient of variation (%)",
    direction: "lower_is_better",
    benchmark: "CV <5% for most analytes; R >0.975",
    source: "ISO 22870",
  },
  {
    department: "Point-of-Care Testing",
    name: "Critical Value Reporting TAT (POCT)",
    phase: "post-analytical",
    unit: "Minutes from verified result to clinician notification",
    direction: "lower_is_better",
    benchmark: "Most labs target <=5-10 min",
    source: "AACC/ADLM POCT Guidance 2020",
  },
  {
    department: "Point-of-Care Testing",
    name: "POCT Device Lockout Rate",
    phase: "pre-analytical",
    unit: "% of POCT device users locked out for non-compliance",
    direction: "lower_is_better",
    benchmark: "Goal: 0%",
    source: "AACC/ADLM 2020; RCPath 2025",
  },
  {
    department: "Point-of-Care Testing",
    name: "POCT Alternative Performance Assessment Completion Rate",
    phase: "analytical",
    unit: "% of POCT devices with completed semiannual APA",
    direction: "higher_is_better",
    benchmark: "100% required by CAP",
    source: "CAP FAQ Glucose Meters; CAP LAP",
  },
  {
    department: "Point-of-Care Testing",
    name: "POC Positive Patient Identification (PPID) Rate",
    phase: "pre-analytical",
    unit: "% of POC tests with confirmed positive patient ID",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "IFCC POCT QI Working Group 2025; ISO 22870",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 7 - Molecular Diagnostics (7 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Molecular Diagnostics",
    name: "Molecular Respiratory Panel TAT",
    phase: "analytical",
    unit: "Hours from specimen receipt to resulted report",
    direction: "lower_is_better",
    benchmark: "Rapid panels: 1-4 hours; batch: up to 24 hours",
    source: "Geisinger/BioFire; NovoPath KPI",
  },
  {
    department: "Molecular Diagnostics",
    name: "Molecular Assay Invalid Rate",
    phase: "analytical",
    unit: "% of runs with invalid results",
    direction: "lower_is_better",
    benchmark: "Platform-specific; tracked internally",
    source: "ASM CPHMC 2017; CLSI MM13",
  },
  {
    department: "Molecular Diagnostics",
    name: "Molecular Assay Repeat/Rerun Rate",
    phase: "analytical",
    unit: "% of runs requiring repeat",
    direction: "lower_is_better",
    benchmark: "Institution- and platform-specific",
    source: "NovoPath; ASM CPHMC 2017",
  },
  {
    department: "Molecular Diagnostics",
    name: "Molecular Assay Positivity Rate",
    phase: "analytical",
    unit: "% of tests positive for target pathogen",
    direction: "lower_is_better",
    benchmark: "Trended for outbreak detection",
    source: "ASM CPHMC 2017",
  },
  {
    department: "Molecular Diagnostics",
    name: "Molecular Calibration/Control Failure Rate",
    phase: "analytical",
    unit: "% of runs with calibration or control failure",
    direction: "lower_is_better",
    benchmark: "Goal: ~0%",
    source: "NovoPath; CLIA 42 CFR 493.1256; CAP LAP",
  },
  {
    department: "Molecular Diagnostics",
    name: "Molecular Assay Proficiency Testing Performance",
    phase: "analytical",
    unit: "% of PT challenges with acceptable results",
    direction: "higher_is_better",
    benchmark: ">=80% per CLIA; ABO/Rh: 100%",
    source: "42 CFR 493.1236",
  },
  {
    department: "Molecular Diagnostics",
    name: "Method Verification Completion Rate (molecular)",
    phase: "analytical",
    unit: "% of new molecular tests verified before patient use",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1253; CLSI MM13; CAP LAP",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 8 - Flow Cytometry (7 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Flow Cytometry",
    name: "Daily Instrument QC Pass Rate",
    phase: "analytical",
    unit: "% of daily QC runs within target ranges",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "Cytometry Part B 2015",
  },
  {
    department: "Flow Cytometry",
    name: "Inter-instrument CV (multi-cytometer labs)",
    phase: "analytical",
    unit: "Coefficient of variation (%) across instruments",
    direction: "lower_is_better",
    benchmark: "Goal: CV <5%",
    source: "Beckman Coulter; EuroFlow",
  },
  {
    department: "Flow Cytometry",
    name: "Specimen Viability/Quality Assessment Rate",
    phase: "pre-analytical",
    unit: "% of specimens meeting minimum viability threshold",
    direction: "higher_is_better",
    benchmark: "Lab-defined thresholds",
    source: "Incite Health 2023; Cytometry B 2015",
  },
  {
    department: "Flow Cytometry",
    name: "Flow Cytometry Proficiency Testing Performance",
    phase: "analytical",
    unit: "% of PT challenges acceptable",
    direction: "higher_is_better",
    benchmark: ">=80% per CLIA/CAP; immunophenotyping: 100%",
    source: "CAP/CLIA; Incite Health 2023",
  },
  {
    department: "Flow Cytometry",
    name: "Panel Validation Sensitivity/Specificity Rate",
    phase: "analytical",
    unit: "% sensitivity and specificity per target population",
    direction: "higher_is_better",
    benchmark: ">=90% commonly cited",
    source: "Incite Health 2023; CAP LAP",
  },
  {
    department: "Flow Cytometry",
    name: "Lot-to-Lot Reagent Variability Acceptance Rate",
    phase: "pre-analytical",
    unit: "% of new reagent lots passing comparison testing",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "Incite Health 2023; CAP LAP",
  },
  {
    department: "Flow Cytometry",
    name: "Flow Cytometry Report TAT",
    phase: "post-analytical",
    unit: "Hours or business days from receipt to finalized report",
    direction: "lower_is_better",
    benchmark: "Typically 24-48 hours; STAT leukemia: <24 hours",
    source: "CAP LAP",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 9 - Send-outs / Reference Lab (6 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Send-outs / Reference Lab",
    name: "Send-out Test Turnaround Time Compliance Rate",
    phase: "post-analytical",
    unit: "% of send-out results received within negotiated TAT",
    direction: "higher_is_better",
    benchmark: "Institution-defined targets",
    source: "COLA QA; 42 CFR 493.1299; CAP LAP",
  },
  {
    department: "Send-outs / Reference Lab",
    name: "Send-out Specimen Acceptance/Rejection Rate",
    phase: "pre-analytical",
    unit: "% of send-out specimens rejected by reference lab",
    direction: "lower_is_better",
    benchmark: "Monitored for trend",
    source: "COLA QA; 42 CFR 493.1249",
  },
  {
    department: "Send-outs / Reference Lab",
    name: "Send-out Order Accuracy Rate",
    phase: "pre-analytical",
    unit: "% of send-out orders with all required information",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "COLA QA; 42 CFR 493.1241",
  },
  {
    department: "Send-outs / Reference Lab",
    name: "Reference Lab Report Receipt Confirmation Rate",
    phase: "post-analytical",
    unit: "% of send-out orders with confirmed report receipt",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "COLA QA; CAP LAP",
  },
  {
    department: "Send-outs / Reference Lab",
    name: "Add-On/Reflex Test Utilization Rate (send-outs)",
    phase: "pre-analytical",
    unit: "% of send-out specimens with add-on or reflex tests",
    direction: "lower_is_better",
    benchmark: "Monitored for trend",
    source: "Institutional standard; CAP LAP",
  },
  {
    department: "Send-outs / Reference Lab",
    name: "Outpatient Order Entry Error Rate",
    phase: "pre-analytical",
    unit: "% of outpatient requisitions with >=1 error",
    direction: "lower_is_better",
    benchmark: "Overall: 4.8%; median institution: 6.0%",
    source: "CAP Q-Probes 1999",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 10 - Specimen Processing / Pre-Analytical (16 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Overall Specimen Rejection Rate",
    phase: "pre-analytical",
    unit: "% of received specimens rejected",
    direction: "lower_is_better",
    benchmark: "Median: 0.31-0.38%; target: 0.28%; threshold: 0.5%",
    source: "CAP Q-Probes 1995; CAP Q-Tracks",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Patient Wristband Error Rate",
    phase: "pre-analytical",
    unit: "% of patients with incorrect or missing wristband",
    direction: "lower_is_better",
    benchmark: "Q-Tracks end: 3.05%; best: <1.0%",
    source: "CAP Q-Tracks 2002",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Specimen Mislabeling Rate (general)",
    phase: "pre-analytical",
    unit: "Labeling errors per 1,000 labels",
    direction: "lower_is_better",
    benchmark: "0.92 per 1,000; target: zero",
    source: "CAP Q-Probes 2008",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Phlebotomy Patient Bruising Rate",
    phase: "pre-analytical",
    unit: "% of patients with bruising post-phlebotomy",
    direction: "lower_is_better",
    benchmark: "Median: 16.7%; best: 7.1%",
    source: "CAP Q-Probes 1991",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Phlebotomy Patient Wait Time",
    phase: "pre-analytical",
    unit: "Minutes from arrival to collection",
    direction: "lower_is_better",
    benchmark: "Median: 6 min; best: 4 min",
    source: "CAP Q-Probes 1991",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Canceled Tests Never Redrawn/Reported Rate",
    phase: "pre-analytical",
    unit: "% of canceled tests where specimen is never redrawn",
    direction: "lower_is_better",
    benchmark: "48.3% in Q-Probes analysis",
    source: "CAP Q-Probes 2014",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Specimen Rejection Lag Time",
    phase: "pre-analytical",
    unit: "Minutes of delay due to specimen rejection",
    direction: "lower_is_better",
    benchmark: "Median lag: 65 minutes",
    source: "CAP Q-Probes 2014",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Requisition/Order Error Rate",
    phase: "pre-analytical",
    unit: "% of orders with incomplete or incorrect information",
    direction: "lower_is_better",
    benchmark: "Outpatient: 4.8%; inpatient not received: 2.9%",
    source: "CAP Q-Probes 1999/1995",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Specimen Transport Temperature Compliance Rate",
    phase: "pre-analytical",
    unit: "% of specimens arriving at correct temperature",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1249; COLA QA",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Inpatient Order Accuracy Rate",
    phase: "pre-analytical",
    unit: "% of inpatient orders correctly transmitted",
    direction: "higher_is_better",
    benchmark: "Median: 99.3%; overall: 97.5%",
    source: "CAP Q-Probes 1995",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Blood Culture Transit Time Compliance Rate",
    phase: "pre-analytical",
    unit: "% of blood cultures with transit time within window",
    direction: "higher_is_better",
    benchmark: "Monitored; impacts bacterial detection",
    source: "CAP Q-Probes 2020",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Stat Test Overuse (% ordered as STAT)",
    phase: "pre-analytical",
    unit: "% of total test orders designated as STAT",
    direction: "lower_is_better",
    benchmark: "Trended for appropriateness",
    source: "CAP Q-Probes 2013",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Hand Hygiene Compliance Rate (phlebotomy)",
    phase: "pre-analytical",
    unit: "% of events with proper hand hygiene",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "TJC NPSG.07.01.01; CDC/WHO",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Two Patient Identifier Compliance Rate",
    phase: "pre-analytical",
    unit: "% of collections using >=2 acceptable patient identifiers",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "TJC NPSG.01.01.01; AABB Standards 34th ed.",
  },
  {
    department: "Specimen Processing / Pre-Analytical",
    name: "Pre-labeling Incident Rate",
    phase: "pre-analytical",
    unit: "Incidents per period of pre-labeled containers",
    direction: "lower_is_better",
    benchmark: "Goal: zero",
    source: "TJC NPSG.01.01.01; AABB Standards 34th ed.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEPARTMENT 11 - General / Cross-Department (32 metrics)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    department: "General / Cross-Department",
    name: "Proficiency Testing (PT) Acceptable Performance Rate",
    phase: "analytical",
    unit: "% of PT challenges graded acceptable",
    direction: "higher_is_better",
    benchmark: "CLIA minimum: >=80%; transfusion: 100%",
    source: "42 CFR 493.1236; CAP PT Manual",
  },
  {
    department: "General / Cross-Department",
    name: "PT Unsatisfactory Performance Rate by Section",
    phase: "analytical",
    unit: "% of PT challenges graded unacceptable per section",
    direction: "lower_is_better",
    benchmark: "US CAP labs: <5-10% per section",
    source: "Scientific Reports 2024; 42 CFR 493.1236",
  },
  {
    department: "General / Cross-Department",
    name: "PT Survey Submission Timeliness Rate",
    phase: "post-analytical",
    unit: "% of PT surveys submitted by deadline",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1236; CAP PT Manual",
  },
  {
    department: "General / Cross-Department",
    name: "PT Failure Root Cause Analysis Completion Rate",
    phase: "post-analytical",
    unit: "% of PT failures with documented RCA",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "Scientific Reports 2024; 42 CFR 493.1239",
  },
  {
    department: "General / Cross-Department",
    name: "Personnel Competency Assessment Completion Rate",
    phase: "pre-analytical",
    unit: "% of testing personnel with all 6 CLIA procedures documented",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CMS CLIA; 42 CFR 493.1451",
  },
  {
    department: "General / Cross-Department",
    name: "New Employee Competency Completion Rate (first year)",
    phase: "pre-analytical",
    unit: "% of new employees with semiannual competency done",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CMS CLIA 42 CFR 493.1451; CAP LAP",
  },
  {
    department: "General / Cross-Department",
    name: "Training Completion Rate for Policy/Procedure Updates",
    phase: "pre-analytical",
    unit: "% of staff completing required training after changes",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP LAP; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Planned Preventive Maintenance (PM) Completion Rate",
    phase: "analytical",
    unit: "% of scheduled PM events completed on time",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP LAP; CLIA 42 CFR 493.1254; AABB",
  },
  {
    department: "General / Cross-Department",
    name: "Unplanned Equipment Downtime Rate",
    phase: "analytical",
    unit: "% of operating hours lost to unplanned downtime",
    direction: "lower_is_better",
    benchmark: "<2% excellent; 2-5% acceptable; >5% concerning",
    source: "KPI Depot Laboratory Equipment Downtime",
  },
  {
    department: "General / Cross-Department",
    name: "Equipment Repair Response Time",
    phase: "analytical",
    unit: "Hours from downtime to restored function",
    direction: "lower_is_better",
    benchmark: "Lab-defined; tracked for trend",
    source: "CAP LAP; Lab Manager Academy",
  },
  {
    department: "General / Cross-Department",
    name: "Critical Value Notification TAT (all departments)",
    phase: "post-analytical",
    unit: "Minutes from authorization to clinician notification",
    direction: "lower_is_better",
    benchmark: "Target: <=5-10 minutes",
    source: "CAP Q-Probes 2008; TJC NPSG.02.03.01",
  },
  {
    department: "General / Cross-Department",
    name: "Critical Value Read-Back Documentation Rate",
    phase: "post-analytical",
    unit: "% of notifications with documented read-back",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "TJC NPSG.02.03.01; CAP LAP",
  },
  {
    department: "General / Cross-Department",
    name: "Critical Value Log Completeness Rate",
    phase: "post-analytical",
    unit: "% of critical value events with complete log entries",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "TJC NPSG.02.03.01; CAP LAP; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Physician/Clinician Satisfaction Score",
    phase: "post-analytical",
    unit: "Mean satisfaction score on 1-5 scale",
    direction: "higher_is_better",
    benchmark: "Mean: 4.0-4.1; goal: >=4.0/5.0",
    source: "CAP Q-Probes 2016/2009",
  },
  {
    department: "General / Cross-Department",
    name: "Nursing Satisfaction Score",
    phase: "post-analytical",
    unit: "Mean satisfaction score on 1-5 scale",
    direction: "higher_is_better",
    benchmark: "Mean: 3.9 (range 2.5-4.6)",
    source: "CAP Q-Probes 2006",
  },
  {
    department: "General / Cross-Department",
    name: "Patient Satisfaction Score (phlebotomy)",
    phase: "pre-analytical",
    unit: "% satisfied or mean score out of 100",
    direction: "higher_is_better",
    benchmark: "Mean: 98.6-99.2 out of 100",
    source: "CAP Q-Probes 1990-1995",
  },
  {
    department: "General / Cross-Department",
    name: "Outpatient Wait Time for Specimen Collection",
    phase: "pre-analytical",
    unit: "Minutes from check-in to collection",
    direction: "lower_is_better",
    benchmark: "Median: 6 min; institution-defined",
    source: "CAP Q-Probes 1991",
  },
  {
    department: "General / Cross-Department",
    name: "Laboratory Complaint Rate",
    phase: "post-analytical",
    unit: "Complaints per 1,000 tests",
    direction: "lower_is_better",
    benchmark: "Monitored and trended",
    source: "42 CFR 493.1239; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Complaint Investigation/Resolution Rate",
    phase: "post-analytical",
    unit: "% of complaints with documented resolution",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1239; COLA QA; TJC PI",
  },
  {
    department: "General / Cross-Department",
    name: "Corrective Action Closure Rate",
    phase: "post-analytical",
    unit: "% of open corrective actions closed on time",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1239; CAP LAP; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Corrective Action Recurrence Rate",
    phase: "post-analytical",
    unit: "% of closed actions where same root cause recurs",
    direction: "lower_is_better",
    benchmark: "Goal: 0%",
    source: "42 CFR 493.1239; CMS SOM D5291",
  },
  {
    department: "General / Cross-Department",
    name: "Internal Audit Completion Rate",
    phase: "post-analytical",
    unit: "% of scheduled audits completed on time",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP LAP; COLA QA; ISO 15189",
  },
  {
    department: "General / Cross-Department",
    name: "Audit Finding Closure Rate",
    phase: "post-analytical",
    unit: "% of audit findings closed within target timeframe",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "CAP LAP; COLA QA; ISO 15189",
  },
  {
    department: "General / Cross-Department",
    name: "LIS Data Integrity Check Completion Rate",
    phase: "analytical",
    unit: "% of scheduled LIS data integrity checks completed",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1299; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Test Report Completeness Rate",
    phase: "post-analytical",
    unit: "% of finalized reports with all required elements",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1291; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Reference Range Update Communication Rate",
    phase: "post-analytical",
    unit: "% of changes communicated to ordering clinicians",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "42 CFR 493.1291; COLA QA",
  },
  {
    department: "General / Cross-Department",
    name: "Quality Management Review Completion Rate",
    phase: "post-analytical",
    unit: "% of scheduled reviews held and documented",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "ISO 15189; CAP LAP; CLSI QSE 12",
  },
  {
    department: "General / Cross-Department",
    name: "Document Review On-Schedule Rate",
    phase: "post-analytical",
    unit: "% of SOPs reviewed within defined cycle",
    direction: "higher_is_better",
    benchmark: "Goal: 100%",
    source: "COLA QA; CAP LAP; CLSI QSE 8",
  },
  {
    department: "General / Cross-Department",
    name: "Method-to-Method Comparison Completion Rate",
    phase: "analytical",
    unit: "% of required comparisons completed per schedule",
    direction: "higher_is_better",
    benchmark: "Goal: 100% per COLA (at least twice/year)",
    source: "COLA QA; 42 CFR 493.1289; CLSI EP9",
  },
  {
    department: "General / Cross-Department",
    name: "ED Physician Satisfaction with Lab TAT Score",
    phase: "post-analytical",
    unit: "Mean satisfaction score on 1-5 scale",
    direction: "higher_is_better",
    benchmark: "Mean: 3.6/5.0 for stat TAT; 3.9/5.0 overall",
    source: "CAP Q-Probes ~2011; CAP Q-Probes 2001",
  },
];

/** Unique department names in display order */
export const PI_STARTER_DEPARTMENTS = [
  "Blood Bank / Transfusion Medicine",
  "Core Lab",
  "Microbiology",
  "Cytology",
  "Histology / Surgical Pathology",
  "Point-of-Care Testing",
  "Molecular Diagnostics",
  "Flow Cytometry",
  "Send-outs / Reference Lab",
  "Specimen Processing / Pre-Analytical",
  "General / Cross-Department",
] as const;

/** Phase display labels */
export const PHASE_LABELS: Record<string, string> = {
  "pre-analytical": "Pre-analytical",
  "analytical": "Analytical",
  "post-analytical": "Post-analytical",
};

/** Phase badge colors (teal family) */
export const PHASE_COLORS: Record<string, string> = {
  "pre-analytical": "#2563eb",
  "analytical": "#01696F",
  "post-analytical": "#7c3aed",
};
