// tests/playwright/homepage-sample-reports.spec.ts
//
// Gate 3 receipt + regression guard for the 2026-06-14 homepage sample-report
// gallery: surfaces the shared SampleReportsSection (real VeritaCheck PDFs
// generated by the production engine) on the homepage as conversion proof.
//
// Run: npx playwright test homepage-sample-reports

import { test, expect } from "@playwright/test";

const BASE = process.env.PW_BASE || "https://www.veritaslabservices.com";

test.describe("Homepage: sample-report gallery", () => {
  test("section renders with downloadable sample reports", async ({ page }) => {
    await page.goto(`${BASE}/`, { waitUntil: "networkidle" });
    await expect(page.getByRole("heading", { name: "See a real signed report" })).toBeVisible();
    const buttons = page.getByRole("button", { name: /Download sample PDF/ });
    expect(await buttons.count()).toBeGreaterThanOrEqual(5);
  });

  test("no mobile overflow at 390px with the new section", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${BASE}/`, { waitUntil: "networkidle" });
    const overflow = await page.evaluate(
      () => document.documentElement.scrollWidth - document.documentElement.clientWidth
    );
    expect(overflow).toBeLessThanOrEqual(0);
  });
});
