import { useSEO } from "@/hooks/useSEO";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

const FAQ_CATEGORIES = [
  {
    category: "About VeritaAssure\u2122",
    items: [
      {
        q: "What is VeritaAssure\u2122?",
        a: "VeritaAssure\u2122 is a SaaS compliance and operations platform built specifically for clinical laboratories. The suite includes VeritaCheck\u2122 for method validation, calibration verification, and EP15 precision studies; VeritaTrack\u2122 for QC task tracking and sign-off; VeritaStock\u2122 for reagent and inventory management; VeritaBench\u2122 for productivity and staffing analytics; plus inspection readiness, test menu regulatory mapping, staff competency documentation, personnel tracking, certificate monitoring, and proficiency testing guidance. Every report includes regulatory citations and a laboratory director or designee review block.",
      },
      {
        q: "Who built VeritaAssure\u2122?",
        a: "VeritaAssure\u2122 was designed and built by Michael Veri, MS, MBA, MLS(ASCP), CPHQ - a laboratory professional with over 25 years in clinical laboratory science. Michael spent 4 years as a Joint Commission surveyor, conducting more than 200 laboratory surveys across the country. He built VeritaAssure\u2122 as someone who lived the compliance burden from both sides of the inspection table.",
      },
      {
        q: "Is VeritaAssure\u2122 a CLIA-approved or accreditation-approved software?",
        a: "VeritaAssure\u2122 is a documentation and compliance management tool. It generates records that laboratories can use to satisfy their regulatory obligations, but it is not itself a regulatory body and does not grant certification or accreditation. Your laboratory director or designee retains final responsibility for all compliance determinations.",
      },
      {
        q: "Does VeritaAssure\u2122 replace my laboratory director or designee?",
        a: "No. Every report and study generated by VeritaAssure\u2122 includes a laboratory director or designee review block. Final approval and clinical determination must be made by the laboratory director or designee. VeritaAssure\u2122 supports compliance documentation - it does not replace professional judgment.",
      },
    ],
  },
  {
    category: "Products and Modules",
    items: [
      {
        q: "What's included in the VeritaAssure\u2122 suite?",
        a: "The suite includes nine production modules: VeritaCheck\u2122 (method validation, calibration verification, EP15 precision), VeritaTrack\u2122 (QC task tracking and sign-off), VeritaStock\u2122 (reagent and inventory management), VeritaBench\u2122 (productivity and staffing analytics), VeritaScan\u2122 (168-item inspection readiness self-assessment), VeritaPT\u2122 (proficiency testing tracker), VeritaMap\u2122 (test menu regulatory mapping), VeritaLab\u2122 (CLIA certificate and accreditation tracking), and VeritaComp\u2122 (competency assessment). VeritaPolicy\u2122 (TJC policy compliance) and VeritaStaff\u2122 (personnel credentialing) are also available. See the roadmap for what's coming next.",
      },
      {
        q: "What is VeritaCheck\u2122?",
        a: "VeritaCheck\u2122 is the method validation and calibration verification module. It supports CLIA TEa-based pass/fail with automated lookup, EP15 precision, EP9 method comparison, and reportable range studies. Every report includes regulatory citations, statistics, and a director review block, exported as a signed PDF.",
      },
      {
        q: "What is VeritaScan\u2122?",
        a: "VeritaScan\u2122 is a 168-item inspection readiness self-assessment across 10 compliance domains, triple-mapped to The Joint Commission standards, CAP checklists, and 42 CFR Part 493. Studies completed in VeritaCheck\u2122 automatically check off corresponding items, so your inspection readiness is always current. Includes 200+ surveys and an executive summary export.",
      },
      {
        q: "What is VeritaTrack\u2122?",
        a: "VeritaTrack\u2122 is a QC task tracking and sign-off module for daily, weekly, and monthly compliance tasks. Assign tasks to staff, capture electronic sign-offs with timestamps, and produce an audit-ready log for inspections.",
      },
      {
        q: "What is VeritaStock\u2122?",
        a: "VeritaStock\u2122 manages reagent and supply inventory: lot tracking, expiration alerts, par levels, FIFO rotation prompts, and burn-rate-based reorder calculations. Designed to eliminate the spreadsheets most labs use today.",
      },
      {
        q: "What is VeritaBench\u2122?",
        a: "VeritaBench\u2122 provides productivity and staffing analytics for laboratory operations: workload by section, performance indicators (PI dashboards), and staffing planning data. Built for hospital and enterprise labs that need to defend headcount and budget decisions.",
      },
      {
        q: "Do modules work together, or are they separate?",
        a: "They're integrated. Studies in VeritaCheck\u2122 automatically check off VeritaScan\u2122 items. Instruments registered in VeritaMap\u2122 feed VeritaCheck\u2122 instrument selection and VeritaComp\u2122 competency programs. Personnel in VeritaStaff\u2122 tie into VeritaComp\u2122 assessments. One subscription, one login, shared data.",
      },
    ],
  },
  {
    category: "Teams and Seats",
    items: [
      {
        q: "Can my team share an account?",
        a: "Yes. Every paid plan includes seats for additional staff members. The owner invites teammates by email; each gets their own login and customizable permissions. Studies, instruments, and inspection records are shared across the team.",
      },
      {
        q: "How are seat permissions configured?",
        a: "The account owner sets permissions per seat: read-only, study-author, instrument-admin, billing-admin, and others. You can scope a seat to specific modules - for example, an inventory manager who only sees VeritaStock\u2122.",
      },
      {
        q: "How many seats are included in each plan?",
        a: "Seat counts scale with plan tier. Clinic includes 2 seats, Community 5, Hospital 15, and Enterprise 25. Seat counts include the account owner, so a 5-seat Community plan is the owner plus 4 invited teammates. See the pricing page or contact info@veritaslabservices.com for specifics on your situation.",
      },
      {
        q: "Can I add more seats later?",
        a: "Each plan tier includes a fixed number of seats. To get more seats, upgrade to the next tier (Clinic to Community, Community to Hospital, or Hospital to Enterprise) from your Account Settings. Tier upgrades are prorated against your current billing period.",
      },
    ],
  },
  {
    category: "Compliance and Standards",
    items: [
      {
        q: "Which accreditation programs does VeritaAssure\u2122 support?",
        a: "VeritaAssure\u2122 aligns with The Joint Commission (TJC), CAP (College of American Pathologists), COLA, and CMS/CLIA requirements. VeritaScan\u2122 items are triple-mapped to TJC standards, CAP checklists, and 42 CFR Part 493. Reports cite the specific regulation each finding addresses.",
      },
      {
        q: "How does VeritaAssure\u2122 handle the CLIA TEa standard?",
        a: "VeritaCheck\u2122 uses CLIA TEa values from federal law (42 CFR \u00a7493.1253) as the default pass/fail threshold for calibration verification. The TEa lookup tool is available at /resources/clia-tea-lookup. You can override TEa with manufacturer or CAP values if your lab's policy requires it.",
      },
      {
        q: "Does VeritaAssure\u2122 work for waived-only labs?",
        a: "Yes. Certificate of Waiver labs are placed in the Clinic tier automatically. Even waived-only labs benefit from VeritaScan\u2122's inspection readiness self-assessment, VeritaStock\u2122 inventory management, and personnel and certificate tracking.",
      },
      {
        q: "Can a non-laboratorian use VeritaAssure\u2122?",
        a: "Yes, but every report still requires a laboratory director or designee review block. VeritaAssure\u2122 is built so a quality manager, lab supervisor, or technologist can complete the work, while the director retains final approval responsibility.",
      },
    ],
  },
  {
    category: "HIPAA and Data Privacy",
    items: [
      {
        q: "Is VeritaAssure\u2122 a HIPAA-covered platform?",
        a: "No. VeritaAssure\u2122 is not designed to store, process, or transmit protected health information (PHI). It is a QC and compliance documentation tool. Users are required to use only de-identified data: sample IDs, QC lot numbers, instrument control values, and non-patient-identifiable information. Do not enter patient names, dates of birth, medical record numbers, or any other PHI into any VeritaAssure\u2122 module.",
      },
      {
        q: "Why isn't VeritaAssure\u2122 a HIPAA-covered platform?",
        a: "Method validation studies, calibration verification, proficiency testing documentation, inspection readiness checklists, and staff competency records do not require patient data. QC work is performed on controls and reference materials, not patient specimens. Compliance documentation references regulatory standards, not patient outcomes. There is no legitimate need for PHI in any function VeritaAssure\u2122 performs.",
      },
      {
        q: "Will you sign a Business Associate Agreement (BAA)?",
        a: "A BAA is available for organizations that require one as part of their vendor compliance program. Contact info@veritaslabservices.com. Because VeritaAssure\u2122 does not process PHI, a BAA is a contractual formality rather than a functional requirement.",
      },
      {
        q: "What data do you collect about me?",
        a: "We collect your name, email address, lab name, CLIA number, and the compliance data you enter into the platform: study results, test menus, inspection responses, and personnel records. We do not collect patient data, and we do not share or sell your data to third parties.",
      },
      {
        q: "Who can see my data?",
        a: "Your data is visible only to you and any seat users you invite. Veritas Lab Services staff may access data for support purposes. We do not sell, share, or disclose your data to third parties.",
      },
    ],
  },
  {
    category: "Data Security",
    items: [
      {
        q: "How is my data protected?",
        a: "All data is transmitted over encrypted HTTPS connections and stored in an isolated database on a secured cloud server. Access requires authentication with your credentials. Passwords are hashed before storage and never stored in plaintext.",
      },
      {
        q: "Where is my data hosted?",
        a: "Data is hosted on US-based cloud infrastructure with industry-standard physical and network security controls. The application server runs on Railway (US-East region); backups go to off-site cold storage. Contact info@veritaslabservices.com for a security questionnaire if your IT team requires one.",
      },
      {
        q: "Do you back up my data?",
        a: "Yes. Your data is backed up nightly to off-site cold storage independent of the application server. Contact info@veritaslabservices.com if you need to recover data.",
      },
      {
        q: "What happens to my data if VeritaAssure\u2122 experiences an outage?",
        a: "Your data is stored on a persistent cloud volume and is not affected by application restarts or brief outages. Nightly snapshots ensure your data can be restored from the most recent backup in the event of a prolonged outage.",
      },
    ],
  },
  {
    category: "Subscriptions and Billing",
    items: [
      {
        q: "What plans are available?",
        a: "VeritaAssure\u2122 offers plans for labs of all sizes, from a single per-study purchase to enterprise subscriptions for large health systems. Plans include seats for your team and the full VeritaAssure\u2122 module suite. Certificate of Waiver labs are always placed in the lowest tier. For current pricing, visit the pricing page.",
      },
      {
        q: "How does pricing scale with lab size?",
        a: "Plans are tiered by lab type, not by per-instrument or per-test volume. Clinic ($499/yr) is for single-CLIA practices. Community ($999/yr) for community hospitals and reference networks. Hospital ($1,999/yr) for full-service hospital labs. Enterprise ($2,999/yr) for health systems with multiple sites. All plans include the full module suite.",
      },
      {
        q: "How is my plan tier determined?",
        a: "During checkout you can enter your CLIA number and we will look it up against CMS data to suggest a plan based on your certificate type and facility size. You can always select a different tier. Certificate of Waiver labs are placed in the Clinic tier.",
      },
      {
        q: "Do you offer a free trial?",
        a: "Yes. All subscription plans include a 14-day free trial. You can use the full platform during the trial; you're only charged when the trial ends. No commitment.",
      },
      {
        q: "Can I try VeritaAssure\u2122 before subscribing?",
        a: "Yes. A fully interactive live demo is available at veritaslabservices.com/demo with no login required. All subscription plans include a 14-day free trial, so you can use the full platform before being billed. You can also run individual VeritaCheck\u2122 studies on a per-study basis without a subscription.",
      },
      {
        q: "What's the difference between the per-study price and the unlimited subscription?",
        a: "Per Study is $25 per validation study, paid one-time, no subscription. It's ideal for labs that run only a handful of studies a year. VeritaCheck\u2122 Unlimited at $299 per year breaks even after just 12 studies and includes all VeritaCheck\u2122 functionality. For full-suite access (VeritaTrack\u2122, VeritaStock\u2122, VeritaBench\u2122, and others), choose Clinic, Community, Hospital, or Enterprise.",
      },
      {
        q: "Do you offer a money-back guarantee?",
        a: "Yes. Subscription plans include a 30-day money-back guarantee on your first charge. We'll refund the first subscription charge in full within 30 days of that charge. One refund per customer; applies to the initial charge only, not renewals or per-study purchases.",
      },
      {
        q: "What payment methods do you accept?",
        a: "Self-service subscriptions are processed by credit or debit card through Stripe. Hospitals and health systems requiring purchase order-based invoicing should contact info@veritaslabservices.com to arrange billing. Payment card information is processed and stored by Stripe and is never stored on our servers.",
      },
      {
        q: "Do you accept purchase orders or invoicing?",
        a: "Yes. Hospitals and health systems can request PO-based invoicing instead of credit card billing. Visit /request-invoice or email info@veritaslabservices.com to set up.",
      },
      {
        q: "Are there discounts available?",
        a: "We offer discount codes for COLA members, conference attendees, and multi-site groups. Email info@veritaslabservices.com if your situation may qualify.",
      },
      {
        q: "Can I cancel at any time?",
        a: "Yes. You can cancel your subscription at any time. Your access will continue through the end of your current billing period.",
      },
    ],
  },
  {
    category: "Data Retention and Cancellation",
    items: [
      {
        q: "What happens to my data if I cancel?",
        a: "Your data is retained for 2 years after your subscription ends. During this period you can reactivate your subscription and regain full access to your historical records. This retention period is designed to align with common laboratory record retention requirements.",
      },
      {
        q: "Can I export my data before canceling?",
        a: "Yes. Every module that generates structured data has an Excel or PDF export function. We recommend exporting your records before canceling if you want local copies.",
      },
      {
        q: "What happens after the 2-year retention period?",
        a: "After 2 years of inactivity, your account and associated data are permanently deleted from our servers. We will notify you by email before this occurs.",
      },
      {
        q: "Can I request deletion of my data before the retention period ends?",
        a: "Yes. Contact info@veritaslabservices.com to request early deletion. We will confirm deletion within 30 days.",
      },
    ],
  },
  {
    category: "Technical and Support",
    items: [
      {
        q: "What browsers does VeritaAssure\u2122 support?",
        a: "VeritaAssure\u2122 works in any modern browser including Chrome, Edge, Firefox, and Safari. No software installation is required.",
      },
      {
        q: "Is there a mobile app?",
        a: "Not currently. VeritaAssure\u2122 is a web-based platform accessible from any device with a browser, but it is optimized for desktop use.",
      },
      {
        q: "Is software validation documentation available?",
        a: "Yes. A software validation template is available for download on the Resources page. Laboratories that require formal software validation documentation as part of their quality system can use this template to document their validation process.",
      },
      {
        q: "Is there a public roadmap?",
        a: "Yes. The product roadmap at /roadmap shows what's shipped, what's in active development, and what's planned next. Customer requests routinely bump items up the priority list.",
      },
      {
        q: "Do you offer consulting services beyond software?",
        a: "Yes. Veritas Lab Services offers laboratory consulting at /services, including mock inspections, method validation strategy, quality management system buildouts, and CLIA application support. Consulting and software are sold separately.",
      },
      {
        q: "How do I schedule a live walkthrough?",
        a: "Visit /book to schedule a 30-minute call with Michael Veri. We'll walk through your specific accreditation situation and the modules most relevant to your lab.",
      },
      {
        q: "How do I get support?",
        a: "Email info@veritaslabservices.com. We aim to respond within 2 business days.",
      },
      {
        q: "Is training available?",
        a: "Clinic and Community plans include a complimentary 1-hour onboarding session via Zoom or Teams with a VeritaAssure\u2122 specialist. Hospital plans include a 2-hour session. Enterprise plans include custom onboarding tailored to your organization. Additional training sessions can be arranged on request.",
      },
    ],
  },
];

export default function FAQPage() {
    useSEO({ title: "FAQ | VeritaAssure™ Lab Compliance Software", description: "Frequently asked questions about VeritaAssure™, CLIA compliance software, method validation, and laboratory inspection readiness tools." });
return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <section className="border-b border-border bg-gradient-to-br from-primary/8 via-transparent to-transparent">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-14 sm:py-20">
          <Badge variant="outline" className="mb-4 text-primary border-primary/30 bg-primary/5 font-medium">
            FAQ
          </Badge>
          <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight mb-4 leading-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl leading-relaxed">
            Everything you need to know about VeritaAssure&#8482; and clinical laboratory compliance.
          </p>
        </div>
      </section>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-12">
        <div className="space-y-8">
          {FAQ_CATEGORIES.map(cat => (
            <div key={cat.category}>
              <h3 className="text-xs font-semibold text-primary uppercase tracking-widest mb-1 pb-2 border-b border-primary/20 scroll-mt-20">
                {cat.category}
              </h3>
              <Accordion type="multiple" className="w-full">
                {cat.items.map((item, i) => (
                  <AccordionItem key={item.q} value={`${cat.category}-${i}`}>
                    <AccordionTrigger className="text-sm font-medium text-foreground hover:text-primary transition-colors leading-snug text-left">
                      {item.q}
                    </AccordionTrigger>
                    <AccordionContent>
                      <p className="text-sm text-muted-foreground leading-relaxed pr-8">{item.a}</p>
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
