// CLIA Regulated and Commonly-Enrolled Analyte Reference Data
// Source: CMS CLIA Proficiency Testing and PT Referral Brochure, revised October 2024
// Subpart I of CLIA regulations - authoritative list of regulated analytes

export interface CliaAnalyte {
  id: string;
  name: string;
  aliases: string[];           // alternate names used in VeritaMap
  specialty: string;
  subspecialty: string;
  tier: "regulated" | "unregulated";
  ptCategory: string;
  notes?: string;
}

export const cliaAnalytes: CliaAnalyte[] = [

  // ─── MICROBIOLOGY - Bacteriology ─────────────────────────────────────────
  {
    id: "bacterial-detection-id",
    name: "Bacterial Detection and Identification",
    aliases: ["bacterial culture", "bacteria id", "bacterial id"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "bacterial-presence-absence",
    name: "Detection of Presence/Absence of Bacteria (without ID)",
    aliases: ["bacterial screen", "bacteria presence"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "antimicrobial-susceptibility",
    name: "Antimicrobial Susceptibility Testing",
    aliases: ["AST", "susceptibility testing", "sensitivity testing", "MIC"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "direct-bacterial-antigen",
    name: "Direct Bacterial Antigen Detection",
    aliases: ["strep antigen", "group A strep", "GAS antigen"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "bacterial-toxin",
    name: "Bacterial Toxin Detection",
    aliases: ["C diff toxin", "clostridium difficile", "CDI", "toxin assay"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "gram-stain",
    name: "Gram Stain",
    aliases: ["gram staining"],
    specialty: "Microbiology",
    subspecialty: "Bacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },

  // ─── MICROBIOLOGY - Mycobacteriology ─────────────────────────────────────
  {
    id: "acid-fast-stain",
    name: "Acid Fast Stain",
    aliases: ["AFB stain", "AFB smear", "mycobacterium stain"],
    specialty: "Microbiology",
    subspecialty: "Mycobacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "mycobacteriology-detection-id",
    name: "Mycobacteriology Detection and Identification",
    aliases: ["TB culture", "mycobacterium culture", "AFB culture"],
    specialty: "Microbiology",
    subspecialty: "Mycobacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "mycobacteriology-presence-absence",
    name: "Detection of Presence/Absence of Mycobacteria (without ID)",
    aliases: ["mycobacteria screen"],
    specialty: "Microbiology",
    subspecialty: "Mycobacteriology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },

  // ─── MICROBIOLOGY - Mycology ──────────────────────────────────────────────
  {
    id: "fungi-detection-id",
    name: "Detection of Fungi and Aerobic Actinomycetes and Identification",
    aliases: ["fungal culture", "yeast culture", "mold culture"],
    specialty: "Microbiology",
    subspecialty: "Mycology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "fungi-presence-absence",
    name: "Detection of Presence/Absence of Fungi (without ID)",
    aliases: ["fungal screen"],
    specialty: "Microbiology",
    subspecialty: "Mycology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "direct-fungal-antigen",
    name: "Direct Fungal Antigen Detection",
    aliases: ["cryptococcal antigen", "aspergillus antigen", "galactomannan"],
    specialty: "Microbiology",
    subspecialty: "Mycology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },

  // ─── MICROBIOLOGY - Parasitology ─────────────────────────────────────────
  {
    id: "parasite-presence-absence",
    name: "Presence or Absence of Parasites",
    aliases: ["ova and parasite", "O&P", "parasite screen"],
    specialty: "Microbiology",
    subspecialty: "Parasitology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "parasite-detection-id",
    name: "Detection and Identification of Parasites",
    aliases: ["parasite identification", "parasite culture"],
    specialty: "Microbiology",
    subspecialty: "Parasitology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "direct-parasite-antigen",
    name: "Direct Parasite Antigen Detection",
    aliases: ["giardia antigen", "cryptosporidium antigen", "malaria antigen"],
    specialty: "Microbiology",
    subspecialty: "Parasitology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },

  // ─── MICROBIOLOGY - Virology ──────────────────────────────────────────────
  {
    id: "viral-antigen-detection",
    name: "Viral Antigen Detection",
    aliases: ["influenza antigen", "RSV antigen", "COVID antigen", "rapid flu"],
    specialty: "Microbiology",
    subspecialty: "Virology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },
  {
    id: "viral-detection-id",
    name: "Viral Detection and Identification",
    aliases: ["viral culture", "PCR viral", "molecular virology"],
    specialty: "Microbiology",
    subspecialty: "Virology",
    tier: "regulated",
    ptCategory: "Microbiology",
  },

  // ─── IMMUNOHEMATOLOGY ────────────────────────────────────────────────────
  {
    id: "abo-group",
    name: "ABO Group",
    aliases: ["ABO", "blood type", "blood typing", "ABO typing"],
    specialty: "Immunohematology",
    subspecialty: "Immunohematology",
    tier: "regulated",
    ptCategory: "Blood Bank / Immunohematology",
  },
  {
    id: "d-rho-typing",
    name: "D (Rho) Typing",
    aliases: ["Rh typing", "Rh", "D antigen", "Rh factor"],
    specialty: "Immunohematology",
    subspecialty: "Immunohematology",
    tier: "regulated",
    ptCategory: "Blood Bank / Immunohematology",
  },
  {
    id: "unexpected-antibody-detection",
    name: "Unexpected Antibody Detection",
    aliases: ["antibody screen", "Antibody Screen", "indirect antiglobulin test", "IAT"],
    specialty: "Immunohematology",
    subspecialty: "Immunohematology",
    tier: "regulated",
    ptCategory: "Blood Bank / Immunohematology",
  },
  {
    id: "compatibility-testing",
    name: "Compatibility Testing",
    aliases: ["crossmatch", "Crossmatch IS", "Crossmatch AHG", "type and crossmatch", "T&C"],
    specialty: "Immunohematology",
    subspecialty: "Immunohematology",
    tier: "regulated",
    ptCategory: "Blood Bank / Immunohematology",
  },
  {
    id: "antibody-identification",
    name: "Antibody Identification",
    aliases: ["Antibody Identification", "antibody ID", "red cell antibody ID"],
    specialty: "Immunohematology",
    subspecialty: "Immunohematology",
    tier: "regulated",
    ptCategory: "Blood Bank / Immunohematology",
  },

  // ─── HEMATOLOGY ──────────────────────────────────────────────────────────
  {
    id: "cell-identification-manual",
    name: "Cell Identification (manual)",
    aliases: ["manual differential", "manual diff", "Manual Differential", "cell ID manual"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
    notes: "Manual cell ID: enroll in the Cell Identification PT module.",
  },
  {
    id: "wbc-differential-automated",
    name: "White Blood Cell (WBC) Differential (automated)",
    aliases: ["Differential", "WBC diff", "differential", "auto diff", "CBC with diff"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
    notes: "Automated WBC differential: enroll in the WBC Differential PT module.",
  },
  {
    id: "erythrocyte-count",
    name: "Erythrocyte Count",
    aliases: ["RBC", "RBC count", "red blood cell count", "red cell count"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
  },
  {
    id: "hematocrit",
    name: "Hematocrit",
    aliases: ["HCT", "Hct", "packed cell volume", "PCV"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
  },
  {
    id: "hemoglobin",
    name: "Hemoglobin",
    aliases: ["Hemoglobin", "HGB", "Hgb", "hemoglobin concentration"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
  },
  {
    id: "leukocyte-count",
    name: "Leukocyte Count",
    aliases: ["WBC", "WBC count", "white blood cell count", "white cell count"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
  },
  {
    id: "platelet-count",
    name: "Platelet Count",
    aliases: ["Platelet Count", "PLT", "platelets", "thrombocyte count"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "regulated",
    ptCategory: "Hematology",
  },
  {
    id: "fibrinogen",
    name: "Fibrinogen",
    aliases: ["fibrinogen", "factor I"],
    specialty: "Hematology",
    subspecialty: "Coagulation",
    tier: "regulated",
    ptCategory: "Coagulation",
  },
  {
    id: "ptt",
    name: "Partial Thromboplastin Time (PTT)",
    aliases: ["PTT", "aPTT", "activated PTT", "partial thromboplastin time"],
    specialty: "Hematology",
    subspecialty: "Coagulation",
    tier: "regulated",
    ptCategory: "Coagulation",
  },
  {
    id: "pt-inr",
    name: "Prothrombin Time (PT/INR)",
    aliases: ["PT", "PT/INR", "INR", "prothrombin time"],
    specialty: "Hematology",
    subspecialty: "Coagulation",
    tier: "regulated",
    ptCategory: "Coagulation",
  },

  // ─── DIAGNOSTIC IMMUNOLOGY - Syphilis Serology ───────────────────────────
  {
    id: "syphilis-qualitative",
    name: "Qualitative Syphilis Testing",
    aliases: ["RPR", "VDRL", "syphilis screen", "treponemal test"],
    specialty: "Diagnostic Immunology",
    subspecialty: "Syphilis Serology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "syphilis-quantitative",
    name: "Quantitative Syphilis Testing",
    aliases: ["RPR titer", "VDRL titer", "syphilis titer"],
    specialty: "Diagnostic Immunology",
    subspecialty: "Syphilis Serology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },

  // ─── DIAGNOSTIC IMMUNOLOGY - General Immunology ──────────────────────────
  {
    id: "alpha1-antitrypsin",
    name: "Alpha-1 Antitrypsin",
    aliases: ["A1AT", "alpha-1 antitrypsin", "AAT"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "afp",
    name: "Alpha-Fetoprotein (AFP tumor marker)",
    aliases: ["AFP", "alpha-fetoprotein"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "anti-hbs",
    name: "Anti-HBs",
    aliases: ["Anti-HBs", "hepatitis B surface antibody", "HBsAb"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "anti-hcv",
    name: "Anti-HCV",
    aliases: ["Anti-HCV", "hepatitis C antibody", "HCV antibody"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "ana",
    name: "Antinuclear Antibody (ANA)",
    aliases: ["ANA", "antinuclear antibody"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "aso",
    name: "Antistreptolysin O (ASO)",
    aliases: ["ASO", "antistreptolysin O", "strep antibody"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "anti-hiv",
    name: "Anti-Human Immunodeficiency Virus (HIV)",
    aliases: ["HIV", "HIV antibody", "anti-HIV", "HIV test", "HIV screen"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "complement-c3",
    name: "Complement C3",
    aliases: ["C3", "complement C3"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "complement-c4",
    name: "Complement C4",
    aliases: ["C4", "complement C4"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "crp-high-sensitivity",
    name: "C-reactive Protein (high sensitivity)",
    aliases: ["hs-CRP", "hsCRP", "high sensitivity CRP", "cardiac CRP"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "hbsag",
    name: "Hepatitis B Surface Antigen (HBsAg)",
    aliases: ["HBsAg", "hepatitis B antigen", "hep B antigen"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "anti-hbc",
    name: "Hepatitis B Core Antibody (Anti-HBc)",
    aliases: ["Anti-HBc", "hepatitis B core antibody", "HBcAb"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "hbeag",
    name: "Hepatitis Be Antigen (HBeAg)",
    aliases: ["HBeAg", "hepatitis B e antigen"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "immunoglobulin-iga",
    name: "Immunoglobulin IgA",
    aliases: ["IgA", "immunoglobulin A"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "immunoglobulin-igg",
    name: "Immunoglobulin IgG",
    aliases: ["IgG", "immunoglobulin G"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "immunoglobulin-igm",
    name: "Immunoglobulin IgM",
    aliases: ["IgM", "immunoglobulin M"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "immunoglobulin-ige",
    name: "Immunoglobulin IgE",
    aliases: ["IgE", "immunoglobulin E", "total IgE"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "infectious-mono",
    name: "Infectious Mononucleosis",
    aliases: ["mono test", "monospot", "heterophile antibody", "EBV heterophile"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "rheumatoid-factor",
    name: "Rheumatoid Factor",
    aliases: ["RF", "rheumatoid factor"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "rubella",
    name: "Rubella",
    aliases: ["rubella antibody", "rubella IgG", "rubella titer"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },

  // ─── CHEMISTRY - Routine Chemistry ───────────────────────────────────────
  {
    id: "alt",
    name: "Alanine Aminotransferase (ALT/SGPT)",
    aliases: ["ALT", "SGPT", "alanine aminotransferase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "albumin",
    name: "Albumin",
    aliases: ["Albumin", "serum albumin"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "alkaline-phosphatase",
    name: "Alkaline Phosphatase",
    aliases: ["ALP", "alk phos", "alkaline phosphatase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "amylase",
    name: "Amylase",
    aliases: ["Amylase", "serum amylase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ast",
    name: "Aspartate Aminotransferase (AST/SGOT)",
    aliases: ["AST", "SGOT", "aspartate aminotransferase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "bilirubin-total",
    name: "Bilirubin, total",
    aliases: ["Bilirubin", "total bilirubin", "T bili", "tbili"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "blood-gas-ph",
    name: "Blood Gas: pH",
    aliases: ["pH", "arterial pH", "blood gas pH"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "blood-gas-pco2",
    name: "Blood Gas: pCO2",
    aliases: ["pCO2", "PCO2", "arterial pCO2"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "blood-gas-po2",
    name: "Blood Gas: pO2",
    aliases: ["pO2", "PO2", "arterial pO2"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "bnp",
    name: "B-natriuretic Peptide (BNP)",
    aliases: ["BNP", "brain natriuretic peptide", "B-natriuretic peptide"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "probnp",
    name: "ProBNP",
    aliases: ["ProBNP", "NT-proBNP", "pro-BNP", "proBNP"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "calcium-total",
    name: "Calcium, total",
    aliases: ["Calcium", "Ca", "total calcium", "serum calcium"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "carbon-dioxide",
    name: "Carbon Dioxide",
    aliases: ["CO2", "carbon dioxide", "bicarbonate", "HCO3", "TCO2"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "chloride",
    name: "Chloride",
    aliases: ["Chloride", "Cl", "serum chloride"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ldl-direct",
    name: "Cholesterol, LDL (direct measurement)",
    aliases: ["LDL", "LDL cholesterol", "direct LDL", "LDL-C"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "cholesterol-total",
    name: "Cholesterol, Total",
    aliases: ["Cholesterol", "total cholesterol", "TC"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "hdl",
    name: "Cholesterol, HDL",
    aliases: ["HDL", "HDL cholesterol", "HDL-C"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "creatine-kinase",
    name: "Creatine Kinase",
    aliases: ["CK", "CPK", "creatine kinase", "creatine phosphokinase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ck-mb",
    name: "Creatine Kinase Isoenzyme (CK-MB)",
    aliases: ["CK-MB", "CKMB", "creatine kinase MB"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "creatinine",
    name: "Creatinine",
    aliases: ["Creatinine", "serum creatinine", "Cr"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ferritin",
    name: "Ferritin",
    aliases: ["Ferritin", "serum ferritin"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ggt",
    name: "Gamma-glutamyl Transferase (GGT)",
    aliases: ["GGT", "GGTP", "gamma-glutamyl transferase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "glucose",
    name: "Glucose",
    aliases: ["Glucose", "blood glucose", "serum glucose", "fasting glucose"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "hba1c",
    name: "Hemoglobin A1c",
    aliases: ["Hemoglobin A1c", "HbA1c", "HgbA1c", "A1c", "glycated hemoglobin"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "iron-total",
    name: "Iron, total",
    aliases: ["Iron", "serum iron", "total iron"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "ldh",
    name: "Lactate Dehydrogenase (LDH)",
    aliases: ["LDH", "lactate dehydrogenase", "LD"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "magnesium",
    name: "Magnesium",
    aliases: ["Magnesium", "Mg", "serum magnesium"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "phosphorus",
    name: "Phosphorus",
    aliases: ["Phosphorus", "phosphate", "PO4", "serum phosphorus"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "potassium",
    name: "Potassium",
    aliases: ["Potassium", "K", "serum potassium"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "psa-total",
    name: "Prostate-specific Antigen (PSA), total",
    aliases: ["PSA", "total PSA", "prostate specific antigen"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "sodium",
    name: "Sodium",
    aliases: ["Sodium", "Na", "serum sodium"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "tibc",
    name: "Total Iron Binding Capacity (TIBC), direct measurement",
    aliases: ["TIBC", "total iron binding capacity"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "total-protein",
    name: "Total Protein",
    aliases: ["Total Protein", "TP", "serum protein", "protein total"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "triglycerides",
    name: "Triglycerides",
    aliases: ["Triglycerides", "TG", "TRIG", "trigs"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "troponin-i",
    name: "Troponin I",
    aliases: ["Troponin I", "TnI", "cTnI", "cardiac troponin I"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "troponin-t",
    name: "Troponin T",
    aliases: ["Troponin T", "TnT", "cTnT", "cardiac troponin T", "Troponin"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "urea-nitrogen",
    name: "Urea Nitrogen",
    aliases: ["BUN", "urea nitrogen", "blood urea nitrogen"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "uric-acid",
    name: "Uric Acid",
    aliases: ["Uric Acid", "urate", "serum uric acid"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "regulated",
    ptCategory: "General Chemistry",
  },

  // ─── CHEMISTRY - Endocrinology ────────────────────────────────────────────
  {
    id: "ca-125",
    name: "Cancer Antigen (CA) 125",
    aliases: ["CA 125", "CA125", "cancer antigen 125"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "cea",
    name: "Carcinoembryonic Antigen (CEA)",
    aliases: ["CEA", "carcinoembryonic antigen"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "cortisol",
    name: "Cortisol",
    aliases: ["Cortisol", "serum cortisol"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "estradiol",
    name: "Estradiol",
    aliases: ["Estradiol", "E2", "17-beta estradiol"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "folate-serum",
    name: "Folate, serum",
    aliases: ["Folate", "folic acid", "serum folate"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "fsh",
    name: "Follicle-stimulating Hormone (FSH)",
    aliases: ["FSH", "follicle stimulating hormone"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "free-thyroxine",
    name: "Free Thyroxine",
    aliases: ["Free T4", "FT4", "free thyroxine"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "hcg",
    name: "Human Chorionic Gonadotropin (HCG)",
    aliases: ["HCG", "hCG", "beta-HCG", "beta hCG", "pregnancy test quantitative"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "lh",
    name: "Luteinizing Hormone (LH)",
    aliases: ["LH", "luteinizing hormone"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "pth",
    name: "Parathyroid Hormone",
    aliases: ["PTH", "parathyroid hormone", "parathormone"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "progesterone",
    name: "Progesterone",
    aliases: ["Progesterone", "serum progesterone"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "prolactin",
    name: "Prolactin",
    aliases: ["Prolactin", "PRL"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "t3-uptake",
    name: "T3 Uptake",
    aliases: ["T3 uptake", "T3U", "thyroid uptake"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "testosterone",
    name: "Testosterone",
    aliases: ["Testosterone", "serum testosterone", "total testosterone"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "t3",
    name: "Triiodothyronine (T3)",
    aliases: ["T3", "triiodothyronine", "total T3"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "tsh",
    name: "Thyroid Stimulating Hormone (TSH)",
    aliases: ["TSH", "thyroid stimulating hormone", "thyrotropin"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "t4",
    name: "Thyroxine (T4)",
    aliases: ["T4", "thyroxine", "total T4"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "vitamin-b12",
    name: "Vitamin B12",
    aliases: ["B12", "vitamin B12", "cobalamin", "cyanocobalamin"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "regulated",
    ptCategory: "Endocrinology",
  },

  // ─── CHEMISTRY - Toxicology ───────────────────────────────────────────────
  {
    id: "acetaminophen",
    name: "Acetaminophen, serum",
    aliases: ["Acetaminophen", "Tylenol level", "APAP", "paracetamol"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "alcohol-blood",
    name: "Alcohol (blood)",
    aliases: ["ETOH", "ethanol", "blood alcohol", "BAL"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "blood-lead",
    name: "Blood Lead",
    aliases: ["Lead", "blood lead", "Pb"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "carbamazepine",
    name: "Carbamazepine, total",
    aliases: ["Carbamazepine", "Tegretol level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "digoxin",
    name: "Digoxin, total",
    aliases: ["Digoxin", "digoxin level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "gentamicin",
    name: "Gentamicin",
    aliases: ["Gentamicin", "gent level", "aminoglycoside"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "lithium",
    name: "Lithium",
    aliases: ["Lithium", "lithium level", "Li"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "phenobarbital",
    name: "Phenobarbital",
    aliases: ["Phenobarbital", "phenobarb level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "phenytoin",
    name: "Phenytoin, total",
    aliases: ["Phenytoin", "Dilantin level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "salicylate",
    name: "Salicylate",
    aliases: ["Salicylate", "aspirin level", "ASA level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "theophylline",
    name: "Theophylline",
    aliases: ["Theophylline", "theophylline level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "tobramycin",
    name: "Tobramycin",
    aliases: ["Tobramycin", "tobramycin level"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "valproic-acid",
    name: "Valproic Acid, total",
    aliases: ["Valproic Acid", "valproate level", "VPA"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },
  {
    id: "vancomycin",
    name: "Vancomycin",
    aliases: ["Vancomycin", "vanc level", "vancomycin trough"],
    specialty: "Chemistry",
    subspecialty: "Toxicology",
    tier: "regulated",
    ptCategory: "Toxicology / TDM",
  },

  // ─── UNREGULATED - Commonly enrolled by labs ─────────────────────────────
  {
    id: "urinalysis-microscopic",
    name: "Urinalysis (microscopic)",
    aliases: ["UA microscopic", "urine microscopy", "microscopic urinalysis", "urine micro"],
    specialty: "Chemistry",
    subspecialty: "Urinalysis",
    tier: "unregulated",
    ptCategory: "Urinalysis",
  },
  {
    id: "lipase",
    name: "Lipase",
    aliases: ["Lipase", "serum lipase"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "unregulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "procalcitonin",
    name: "Procalcitonin",
    aliases: ["PCT", "procalcitonin"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "unregulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "vitamin-d",
    name: "Vitamin D, 25-hydroxy",
    aliases: ["Vitamin D", "25-OH vitamin D", "25-hydroxyvitamin D", "Vit D"],
    specialty: "Chemistry",
    subspecialty: "Endocrinology",
    tier: "unregulated",
    ptCategory: "Endocrinology",
  },
  {
    id: "d-dimer",
    name: "D-Dimer",
    aliases: ["D-Dimer", "d-dimer", "fibrin degradation products"],
    specialty: "Hematology",
    subspecialty: "Coagulation",
    tier: "unregulated",
    ptCategory: "Coagulation",
  },
  {
    id: "lactate",
    name: "Lactate",
    aliases: ["Lactate", "lactic acid", "blood lactate"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "unregulated",
    ptCategory: "Special Chemistry",
  },
  {
    id: "ammonia",
    name: "Ammonia",
    aliases: ["Ammonia", "serum ammonia", "plasma ammonia"],
    specialty: "Chemistry",
    subspecialty: "Routine Chemistry",
    tier: "unregulated",
    ptCategory: "General Chemistry",
  },
  {
    id: "crp-standard",
    name: "C-reactive Protein (standard)",
    aliases: ["CRP", "C-reactive protein", "standard CRP"],
    specialty: "Diagnostic Immunology",
    subspecialty: "General Immunology",
    tier: "unregulated",
    ptCategory: "Immunology / Serology",
  },
  {
    id: "urine-protein-total",
    name: "Urine Protein, total",
    aliases: ["urine protein", "24-hour urine protein", "total urine protein"],
    specialty: "Chemistry",
    subspecialty: "Urinalysis",
    tier: "unregulated",
    ptCategory: "Urinalysis",
  },
  {
    id: "microalbumin",
    name: "Urine Microalbumin",
    aliases: ["microalbumin", "urine microalbumin", "albumin/creatinine ratio", "ACR"],
    specialty: "Chemistry",
    subspecialty: "Urinalysis",
    tier: "unregulated",
    ptCategory: "Urinalysis",
  },
  {
    id: "esr",
    name: "Erythrocyte Sedimentation Rate (ESR)",
    aliases: ["ESR", "sed rate", "sedimentation rate"],
    specialty: "Hematology",
    subspecialty: "Hematology",
    tier: "unregulated",
    ptCategory: "Hematology",
  },
];

// PT program finder links - category level (Phase 1)
// Specific catalog numbers will be added in a future phase
export const ptCategoryLinks: Record<string, { cap: string; api: string; capLabel: string; apiLabel: string }> = {
  "General Chemistry": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Special Chemistry": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Endocrinology": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Toxicology / TDM": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Hematology": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Coagulation": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Blood Bank / Immunohematology": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Microbiology": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Immunology / Serology": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
  "Urinalysis": {
    cap: "https://www.cap.org/laboratory-improvement/proficiency-testing/find-a-pt-program",
    api: "https://www.api-pt.com",
    capLabel: "CAP Program Finder",
    apiLabel: "API PT Programs",
  },
};
