// server/inventoryPin.ts
//
// Wave K1 (2026-06-07). Helpers for the lab's Inventory PIN. The PIN is
// a 6-digit numeric code generated by the lab director (or admin) and
// shared with bench techs who need to take inventory but don't have a
// writer seat. Hashed at rest with pbkdf2-sha256 + a per-lab 16-byte
// salt. 1,000,000 PIN values × 100,000 pbkdf2 iterations × 5-failure
// lockout makes brute force impractical even with leaked hashes; for
// the inventory threat model (no PHI, no money, only reagent counts)
// that's the right boundary.

import crypto from "crypto";

const PBKDF2_ITERATIONS = 100_000;
const PBKDF2_KEYLEN = 32;
const PBKDF2_DIGEST = "sha256";
const SALT_BYTES = 16;

// Generate a random 6-digit numeric PIN. Uses crypto.randomInt so the
// distribution is uniform and the value is unpredictable.
export function generate6DigitPin(): string {
  return String(crypto.randomInt(0, 1_000_000)).padStart(6, "0");
}

// Hash the PIN with a fresh salt. Returns both so the caller can write
// them to the labs row.
export function hashPin(pin: string): { hash: string; salt: string } {
  const salt = crypto.randomBytes(SALT_BYTES).toString("hex");
  const hash = crypto
    .pbkdf2Sync(pin, salt, PBKDF2_ITERATIONS, PBKDF2_KEYLEN, PBKDF2_DIGEST)
    .toString("hex");
  return { hash, salt };
}

// Constant-time verify. Returns true iff the supplied PIN matches the
// stored hash for the given salt. Uses crypto.timingSafeEqual to avoid
// per-character timing leaks.
export function verifyPin(pin: string, hash: string, salt: string): boolean {
  if (!pin || !hash || !salt) return false;
  let candidate: Buffer;
  let stored: Buffer;
  try {
    candidate = crypto.pbkdf2Sync(pin, salt, PBKDF2_ITERATIONS, PBKDF2_KEYLEN, PBKDF2_DIGEST);
    stored = Buffer.from(hash, "hex");
  } catch {
    return false;
  }
  if (candidate.length !== stored.length) return false;
  return crypto.timingSafeEqual(candidate, stored);
}
